[package]
name = "xtask"
version = "1.0.0"
edition = "2021"

[dependencies]
build-script = { path = "../crates/build-script" }
bindgen = { workspace = true }
strum = { workspace = true }
log = { workspace = true }
tracel-xtask = { workspace = true }
