[package]
name = "xtask"
version = "1.0.0"
edition = "2021"

[dependencies]
cubecl-hip-sys = { path = "../crates/cubecl-hip-sys" }
bindgen = { workspace = true }
strum = { workspace = true }
log = { workspace = true }
tracel-xtask = { workspace = true }
